<!-- START of: finna - Auth/Shibboleth/login_suomifi.phtml -->
<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<div>
  <div class="login-col shibboleth-login">
    <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" data-lightbox-ignore>
      <img src="<?=$this->imageLink('login_suomifi.png') ?>" alt="<?=$this->escapeHtmlAttr($this->translate("Suomifi Login")) ?>">
      <span class="sr-only"><?=$this->transEsc('Suomifi Login')?></span>
    </a>
  </div>
  <div class="login-col">
    <i class="fa fa-info3" aria-hidden="true"></i>
    <div class="login-description">
      <p class="login-info">
       <?=$this->translate('login_desc_connect_card_html') ?>
      </p>
    </div>
    <div class="login-description shibboleth">
      <?=$this->translate('login_desc_suomifi_html')?>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<?php
  $language = $this->layout()->userLang;
  if (!in_array($language, ['fi', 'sv', 'en-gb'])) {
    $language = 'en-gb';
  }
?>
<?=$this->partial("Auth/Shibboleth_suomifi/terms_$language.phtml") ?>
<!-- END of: finna - Auth/Shibboleth/login_suomifi.phtml -->
