<?php
  $form = $this->form;
  $form->prepare();

  $title = $form->getTitle();
  $title = !empty($title)
    ? $this->transEsc($title) : null;
?>
<?php if ($title): ?>
  <?php $this->headTitle($title); ?>
  <?php if ($this->layout()->getTemplate() !== 'layout/lightbox'): ?>
    <h1><?=$title?></h1>
  <?php else: ?>
    <h2><?=$title?></h2>
  <?php endif; ?>
<?php endif; ?>
<p><?= $this->translate($form->getSubmitResponse()) ?></p>
