<!-- START of: finna - myresearch/r2termsofuse.phtml -->
<?php
  // Set up page title:
  $this->headTitle($this->translate('R2_termsofuse_title'));

  // Set up breadcrumbs:
  $currPage = 'R2TermsOfUse';
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc($currPage) . '</li>';
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'r2-termsofuse']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="clearfix mylist-header hidden-print">
    <div>    
      <?=$this->flashmessages()?>
    </div>
    <div class="useraccount-header">
      <h2><?=$this->transEsc('R2_termsofuse_title')?></h2>
    </div>
    <div><?=$this->translate('R2_termsofuse_content_html')?></div>
  </div>
</div>
<!-- END of: finna - myresearch/r2termsofuse.phtml -->
