<h4 class="panel-title">
  <a data-toggle="collapse" href="#collapse<?=$this->escapeHtmlAttr($this->id)?>"><?=$this->translate('organisation-info-contact')?></a>
</h4>
<div id="collapse<?=$this->escapeHtmlAttr($this->id)?>" class="panel-collapse collapse in">
  <div class="email-contact info-element">
    <strong><?=$this->translate('organisation-info-email')?></strong>
    <p><i class="fa fa-envelope"></i> <a href="#" class="email" itemprop="email"><span class="email"></span></a></p>
  </div>
  <div class="address-contact info-element">
    <strong><?=$this->translate('organisation-info-address')?></strong>
    <p></p>
  </div>
  <div class="phone-numbers info-element">
    <strong><?=$this->translate('organisation-info-phone-numbers')?></strong>
    <p></p>
  </div>
</div>

    