<?
  $this->headScript()->appendFile("finna-organisation-info.js");
  $this->headScript()->appendFile("finna-organisation-info-widget.js");
?>
<div class="organisation-info" data-parent="<?=$this->escapeHtmlAttr($this->id)?>" data-target="<?=$this->escapeHtmlAttr($this->target)?>" data-init="<?=$this->target == 'widget' ? '1' : '0'?>">
<? if ($this->target == 'widget'): ?>
  <div class="row">
    <div class="col-xs-12">
      <h2><?=$this->transEsc('organisation-info-title');?></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="loader"><i class="fa fa-spin fa-spinner"></i></div>
    </div>
  </div>
  <div class="row content hide">
    <div class="col-md-8 col-lg-7 col-xs-12 info">
      <h4>
        <select name="organisation" class="organisation form-control form-inline"></select>
        <span class="is-open open info-element"><?=$this->translate('organisation-info-is-open')?></span>
        <span class="is-open closed info-element"><?=$this->translate('organisation-info-is-closed')?></span>
      </h4>
<? endif ?>
      <div class="info schedules">
        <div class="week-navi-holder">
          <i class="fa fa-arrow-left prev-week week-navi" data-dir="-1"></i>
          <span class="week-text"><?=$this->translate('organisation-info-schedule-week')?> <span class="num"></span></span>
          <i class="fa fa-arrow-right next-week week-navi" data-dir="+1"></i>
        </div>
        <div class="loader"><i class="fa fa-spin fa-spinner"></i></div>
        <div class="content">
          <table class="opening-times-week">
            <tbody>
              <tr class="template hide">
                <td class="date"></td>
                <td>
                  <ul>
                    <li>
                      <span class="day">
                        <span class="name"></span><span class="info"></span>
                      </span>
                      <span class="day staff hide">
                        <span class="name"><?= $this->translate('organisation-info-schedule-staff');?></span><span class="info hide"></span>
                      </span>
                      <span class="time">
                        <span class="opens"></span> - <span class="closes"></span>
                      </span>
                      <span class="time closed-today hide"><?=$this->translate('organisation-info-is-closed')?></span>
                    </li>
                  </ul>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="no-schedules info-element"><?=$this->translate('organisation-info-no-schedule')?></div>
        <div class="mobile-schedule-link-template hide"><a href="#"></a></div>
        <div class="mobile-schedules info-element"></div>
      </div>
      <div class="schedules-info info-element"></div>
<? if ($this->target == 'widget'): ?>
    </div>
    <div class="col-md-4 col-lg-5 col-xs-12">
      <a href="#" target="_blank" class="facility details"><img src="<?=$this->imageLink('noCover2.gif')?>" alt="" class="facility-image"></a>
      <div class="contact-links">
        <a href="#" class="email info-element"><span class="btn btn-open-widget"><i class="fa fa-at"></i></span></a>
        <span class="btn btn-open-widget phone info-element" data-toggle="tooltip" data-placement="bottom" data-html="true" data-original-title=""><i class="fa fa-phone-square"></i></span></a>
        <a href="#" target="_blank" class="route info-element"><span class="btn"><i class="fa fa-bus"></i><span class="sr-only"><?=$this->transEsc('organisation-info-service-print') ?></span></span></a>
        <a href="#" target="_blank" class="facebook info-element"><span class="btn"><i class="fa fa-facebook-square"></i><span class="sr-only"><?=$this->transEsc('organisation-info-service-print') ?></span></span></a>
      </div>
      <div class="map info-element"><a href="#" target="_blank"><i class="fa fa-map-marker"></i> <span class="map-address">Linnankatu 2 20100 Turku</span></a></div>
      <div class="details-link info-element"><a href="#" target="_blank" class="details"><i class="fa fa-home"></i> <?=$this->translate('organisation-info-details')?></a></div>
      <div class="services">
        <span class="btn btn-open-widget btn-round service-wifi info-element" title="<?=$this->translate('organisation-info-service-wifi')?>">
          <i class="fa fa-wifi"></i>
          <span class="sr-only"><?=$this->transEsc('organisation-info-service-wifi') ?></span>
        </span>
        <span class="btn btn-open-widget btn-round service-print info-element" title="<?=$this->translate('organisation-info-service-print')?>">
          <i class="fa fa-print"></i>
          <span class="sr-only"><?=$this->transEsc('organisation-info-service-print') ?></span>
        </span>
      </div>
    </div>
  </div>
<? endif ?>
</div>
