<? $this->headScript()->appendFile('finna-survey.js'); ?>
<div id="survey">
  <div class="icon-background"></div>
  <a href="#" class="icon close-survey"><i class="fa fa-close"></i></a>
  <h2><?=$this->translate('survey-title')?></h2>
  <h3><?=$this->translate('survey-text')?></h3>
  <a target="_blank" href="<?=$this->escapeHtmlAttr($this->url)?>" class="btn btn-primary"><?=$this->translate('survey-btn-ok')?></a>
  <p><a href="#" class="close-survey"><?=$this->translate('survey-btn-cancel')?></a></p>
</div>
