<!-- START of: finna - RecordDriver/DefaultRecord/collection-record.phtml -->
<h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>
<a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->transEsc('View Full ' . ($this->driver->isCollection() ? 'Collection' : 'Record'))?></a>

<table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
  <?php $summary = $this->driver->getSummary(); $summary = $summary[0] ?? false; ?>
  <?php if ($summary): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Description')?>: </th>
      <td><?=$this->escapeHtml($summary)?></td>
    </tr>
  <?php endif; ?>

  <?php $results = $this->driver->getNonPresenterAuthors(); ?>
  <?php if ($results): ?>
    <tr valign="top">
      <th><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </th>
    <?php if ($results): ?>
        <span class="recordAuthors">
        <?php foreach($results as $index => $author): ?>
          <?=($index > 0 ? '; ' : '')?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
        <?php endforeach; ?>
        </span>
      <?php endif; ?>
      <?php if ($containerTitle): ?>
        <?php
          $containerSource = $this->driver->getSourceIdentifier();
          $containerID = $this->driver->getContainerRecordID();
        ?>
        <span class="recordContainerReference">
          <?=$this->transEsc('Published in')?> <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('title', $containerTitle))?>"><?=$this->escapeHtml($containerTitle)?></a>
          <?php $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </span>
      <?php endif; ?>
    </tr>
  <?php endif; ?>

  <?php $authors = $this->driver->getDeduplicatedAuthors(); ?>
  <?php if (isset($authors['main']) && !empty($authors['main'])): ?>
    <tr valign="top">
      <th><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </th>
      <td>
        <?php $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':'; '?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
      </td>
    </tr>
  <?php endif; ?>

  <?php if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
    <tr valign="top">
      <th><?=$this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Author' : 'Corporate Authors')?>: </th>
      <td>
        <?php $i = 0; foreach ($authors['corporate'] as $corporate => $roles): ?><?=($i++ == 0)?'':'; '?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $corporate['name'], $corporate, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Language')?>: </th>
      <td><?php foreach ($langs as $lang): ?><?= $this->transEsc($lang)?><br/><?php endforeach; ?></td>
    </tr>
  <?php endif; ?>

  <?php $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Format')?>: </th>
      <td><?=$this->record($this->driver)->getFormatList()?></td>
    </tr>
  <?php endif; ?>

  <?php $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Access')?>: </th>
      <td>
        <?php foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Related Items')?>: </th>
      <td>
        <?php foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<!-- END of: finna - RecordDriver/DefaultRecord/collection-record.phtml -->
