<?php //Don't add START and END comments ?>
<?php
$fields = [
  'inspector', 'notification', 'number', 'date', 'format', 'reason', 'length', 'runningtime',
  'taxclass', 'agerestriction', 'inspectiontype', 'part', 'office', 'subject'
];
?>
<?php if(!empty($data)): ?>
  <div class="truncate-field">
    <table class="record-data">
      <?php foreach($data as $d): ?>
        <?php foreach ($fields as $key): ?>
          <?php if (empty($d[$key])) { continue; } ?>
          <tr>
            <td><?=$this->transEsc("kavi_{$key}")?></td>
            <td><?=$this->escapeHtml($d[$key])?></td>
          </tr>
        <?php endforeach; ?>
        <tr><td colspan="2">&nbsp;</td></tr>
      <?php endforeach; ?>
    </table>
  </div>
<?php endif; ?>
