<?php //Don't add START and END comments ?>
<?php $extendedData = $this->driver->tryMethod('getTitleStatementsExtended'); if (!empty($extendedData)): ?>
  <div class="additional-information">
    <?php foreach ($extendedData as $i => $item): ?>
      <?= $i > 0 ? '<br/>' : '' ?>
      <?= $this->escapeHtml($item['text']) ?>
      <?php $url = $item['url'] ?? ''; if (!empty($url)): ?>
        (<a target="_blank" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url))?>"><?=$this->escapeHtml($this->truncateUrl($url))?></a>)
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php elseif (!empty($data)): ?>
  <div class="additional-information"><?=$this->escapeHtml($data) ?></div>
<?php endif; ?>
