<?
  $list = $this->results->getListObject();
  $user = $this->auth()->isLoggedIn();
?>

<input type="hidden" name="user_id" value="<?=$user->id ?>">
<input type="hidden" name="list_id" value="<?=$list->id ?>">
<h2><?=$this->transEsc('Sort manually');?></h2>
  <div class="row">
    <div class="col-xs-12">
      <button type="button" id="save_order" value="save_order" class="btn btn-primary"><?=$this->transEsc('Save Order');?></button>
      <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="false"><?=$this->transEsc('Reset');?></button>
    </div>
    <div id="error-message" class="col-xs-12" style="display: none;">
        <?=$this->transEsc('Saving own order failed');?>
    </div>
  </div>
  <ol id="sortable" class="sortable-favorite-list">
    <? foreach ($this->results->getResults() as $i=>$current): ?>
      <li id="<?=$current->getUniqueID() ?>"><input hidden value="<?=$current->getUniqueID() ?>"><h4><?=$current->getTitle()?><i class="fa fa-arrow-down"></i><i class="fa fa-arrow-up"></i></h4><p><?=$this->record($current)->getFormatList() ?></p></li> 
    <? endforeach; ?>
  </ol>
<script>finna.myList.initFavoriteOrderingFunctionality();</script> 
