<?
    $this->layout()->searchbox = false;
    $this->headTitle($this->translate('terms_of_service_title'));
?>
<!-- START of: finna - myresearch/terms.phtml -->
<h2 class="lightbox-header"><?=$this->transEsc('terms_of_service_title')?></h2>
<div class="terms-of-service">
  <form name="termsForm"  method="post" action="<?=$this->url('myresearch-userlogin')?>">
    <p><?= $this->translate('terms_of_service_text_html'); ?></p>
    <p><label><input type="checkbox" name="acceptTerms" value="1"> <?= $this->translate('terms_of_service_checkbox'); ?></p></label>
    <input type="submit" class="btn btn-primary submit disabled" name="submit" value="<?=$this->transEsc('terms_of_service_yes')?>">
    <input type="submit" class="btn btn-primary" name="cancel" value="<?=$this->transEsc('terms_of_service_no')?>">
  </form>
</div>
<script type="text/javascript">
$(document).ready(function() {
  finna.layout.initTermsOfServiceCheckbox(<?=$this->lightbox ? 'true' : 'false' ?>);
});  
</script>
<!-- END of: finna - myresearch/terms.phtml -->
