<?
    $this->layout()->searchbox = false;
    $this->headTitle($this->translate('terms_of_service_title'));
?>
<!-- START of: finna - myresearch/terms.phtml -->
<h2 class="lightbox-header"><?=$this->transEsc('terms_of_service_title')?></h2>
<div class="terms-of-service">
  <form name="termsForm" method="post" action="<?=$this->url('myresearch-userlogin')?>" data-toggle="validator">

    <p><?= $this->translate('terms_of_service_text_html'); ?></p>
    <p><label><input type="checkbox" name="acceptTerms" value="1" required> <?= $this->translate('terms_of_service_checkbox', ['%%terms%%' => $this->url('content-page', ['page' => 'terms_conditions'])]); ?></p></label>
    <input type="submit" class="btn btn-primary submit" name="submit" value="<?=$this->transEsc('Send')?>">
  </form>
</div>
<?
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$lightbox = $this->lightbox ? 'true' : 'false';
$js = <<<JS
  if ($.isReady) {
    $('.terms-of-service form').validator();
  } else {
    $(document).ready(function(){
      $('.terms-of-service form').validator();
    });
  }
JS;

echo $this->inlineScript()->appendScript($js);
?>
<!-- END of: finna - myresearch/terms.phtml -->
