<h4>
  <i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc('metalib_searchsets')?>
  <? if (!$this->translationEmpty('tooltip_facet_html')): ?><span class="tooltip-facet pull-right" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?=$this->transesc('tooltip_facet_html')?>"><i class="fa fa-info-big"></i></span><? endif; ?>
</h4>

<div class="search-sets">
  <? $cnt = 0; ?>
  <? foreach ($this->sets as $set => $label): ?>
  <label class="radiobutton" for="set_<?=$cnt?>">
    <input id="set_<?=$cnt++?>" name="searchSet" type="radio" value="<?=$this->escapeHtmlAttr($set)?>"<?= $currentSet == $set ? ' checked="checked"': ''?> /><?= $this->transEsc($label)?></label><br>
  <? endforeach ?>
</div>

<? if ($this->recentSets): ?>
<div class="search-sets recent" class="truncateField">
  <p><?= $this->translate('Recently Used Databases')?></p>
  <div>
    <? foreach ($this->recentSets as $set => $label): ?>
    <label class="radiobutton" for="set_<?=$cnt?>">
      <input id="set_<?=$cnt++?>" name="searchSet" type="radio" value="<?=$this->escapeHtmlAttr($set)?>"<?= $currentSet == $set ? ' checked="checked"': ''?> /><?= $this->transEsc($label)?></label><br>
    <? endforeach; ?>
  </div>  
<? endif; ?>
