<div class="title-hold">
  <? if ($illRequestLink): ?>
    <a class="expandedCheckILLRequest modal-link placeILLRequest btn btn-primary" href="<?=$this->recordLink()->getRequestUrl($illRequestLink)?>"  title="<?=$this->transEsc("ill_request_check_text")?>"><?=$this->transEsc("ill_request_check_text")?></a>
  <? endif; ?>
  <? $holdingTitleHold = $driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold modal-link btn btn-primary hidden-print" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"> <?=$this->transEsc('title_hold_place')?></a>
  <? elseif ($user): ?>
    <? $patron = $ils->loginAvailable() && $user->cat_username ? $ils->patronLogin($user->cat_username, $user->getCatPassword()) : null; if ($patron): ?>
      <? if ($profile = $ils->getMyProfile($patron)): ?>
        <? if (!empty($profile['blocks'])): ?>
          <?=$this->transEsc('hold_error_blocked'); ?>
        <? elseif (!$illRequestLink && !$holdLinks): ?>
          <?=$this->transEsc('title_cant_place_hold'); ?>
        <? endif; ?>
      <? endif; ?>
    <? endif; ?>
  <? endif; ?>
</div>