<?php
$data = $this->driver->getExternalData();
?>

<?php if ($tbl = $data['fullResImages'] ?? null): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'images', 'data' => $tbl]); ?>
<?php endif; ?>

<?php if ($tbl = $data['OCRImages'] ?? null): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'ocr', 'data' => $tbl]); ?>
<?php endif; ?>


<?php if ($tbl = $data['physicalItems'] ?? null): ?>
<div role="table" class="external-data physical-items" aria-label="<?= $this->transEsc('external_data_tab_physical_items')?>">
  <div role="row" class="tbl-row headers">
    <div role="cell" class="tbl-cell tbl-left"><span role="columnheader"><?= $this->transEsc('external_data_tab_physical_item')?></span></div>
    <div role="cell" class="tbl-cell tbl-right"><span role="columnheader"><?= $this->transEsc('external_data_tab_physical_location')?></span></div>
  </div>
  <?php foreach ($tbl as $item): ?>
  <div role="row" class="tbl-row">
    <div class="tbl-cell tbl-left" role="cell"><?=$item['type']?></div>
    <div class="tbl-cell tbl-right location" role="cell">
      <span class="location-name"><?=$item['location']?></span>
      <?php if (!empty($item['service'])): ?>
      <span class="service alert alert-info"><?= $this->translate('external_data_tab_physical_service')?></span>
      <?php endif; ?>
    </div>
  </div>
  <?php endforeach; ?>
<?php endif; ?>
