<!-- START of: finna - Helpers/R2RestrictedRecordPermission.phtml -->
<?php
  $setupJS = [];
  $registerFormUrl = $this->url('r2feedback-form', ['id' => 'R2Register']);
  if ($this->id) {
    $registerFormUrl
      .= '?recordId=' . $this->escapeHtmlAttr($this->id)
      . ($this->collection ? '&collection=1' : '');
  }
?>
<?php if ($this->weakLogin): ?>
  <div class="r2-restricted-record-register alert alert-danger" role="alert">
    <p><strong><?= $this->translate('R2_register_weak_loginmethod') ?></strong></p>
  </div>
<?php elseif (!$this->user && $this->id): ?>
  <?php
    // Register prompt on record page
    $setupJS['initModal'] = true;
    // Explicitly redirect Collection page login to Record controller
    $registerFormUrl = $this->url('r2record', ['id' => $this->id])
      . '?login=true'
      . '&recordId=' . $this->escapeHtmlAttr($this->id)
      . ($this->collection ? '&collection=1' : '');
  ?>
  <?= $this->partial('Helpers/R2RestrictedRecordPrompt.phtml', compact('registerFormUrl', 'showInfo', 'showInfoLink', 'note', 'registerLabel', 'instructions')) ?>
<?php elseif ($this->blocklisted): ?>
  <div class="authorization-notification alert alert-danger" role="alert"><?= $this->translate('R2_accessrights_blocklisted_html', ['%%name%%' => $this->name, '%%url%%' => $this->url('feedback-home'), '%%date_added%%' => $this->blocklistedDate]) ?></div>
<?php elseif ($this->registered): ?>
  <div class="r2-restricted-record-register">
    <?php if ($this->note): ?>
      <div><?= $this->translate($this->note) ?></div>
    <?php endif ?>
    <div class="register">
      <div class="register-btn"><a href="<?= $this->url('myresearch-r2accessrights') ?>" class="btn btn-primary btn-r2-register"><i class="fa fa-research"></i> <?=$this->transEsc($this->registerLabel)?></a></div>
      <?php if ($this->showInfoLink): ?>
        <p><?=$this->translate('R2_register_read_more_html', ['%%url%%' => $this->url('content-page', ['page' => 'tutkijasali'])])?></p>
      <?php endif ?>
    </div>
  </div>
<?php else: ?>
   <?php
   // Register prompt outside record page.
   if ($this->sessionExpired) {
     $setupJS['initModal'] = true;
     $setupJS['openModal'] = true;
   }
   $linkUrl = $this->user ? $registerFormUrl : $this->url('myresearch-r2accessrights');
   ?>
   <?= $this->partial('Helpers/R2RestrictedRecordPrompt.phtml', compact('registerFormUrl', 'showInfo', 'showInfoLink', 'note', 'registerLabel', 'instructions')) ?>
<?php endif; ?>

<?php
if (!empty($setupJS)) {
  $script = '$(document).ready(function() {';
  foreach ($setupJS as $type => $mode) {
    switch ($type) {
      case 'initModal':
        $script .= 'finna.R2.initModal();';
        break;
      case 'openModal':
        // Session expired, prompt to re-register
        $modalContent = '<h2>' . $this->translate('R2_session_expired_title') . '</h2>';
        $modalContent .= '<p>' . $this->translate('R2_session_expired') . '</p>';
        $modalContent .= '<div class="r2-register">';
        $modalContent .= '<div class="register-btn"><a onClick="finna.R2.openRegistration();" class="btn btn-primary btn-r2-register"><i class="fa fa-research"></i> ' . $this->translate($this->registerLabel) . '</a></div>';
        $modalContent .= '<p><a href="#" onClick="VuFind.lightbox.close(); return false;">' . $this->translate('R2_session_expired_cancel') . '</a></p>';
        $modalContent .= '</div>';

        $this->headScript()->prependScript("VuFind.R2Registration = '" . $registerFormUrl . "';");
        $script .= 'VuFind.lightbox.render(\'' . $modalContent . '\');';
        break;
    }
  }
  $script .= '});';
  echo $this->headScript()->appendFile('finna-R2.js');
  $this->headScript()->appendScript($script);
}
?>
<!-- END of: finna - Helpers/R2RestrictedRecordPermission.phtml -->
