<div class="public-list-embed">
  <div class="clearfix hidden-print">
    <div class="public-list-row">
      <?php if ($this->title): ?><h<?=$this->headingLevel?>><?= $this->title ?></h<?=$this->headingLevel?>><?php endif ?>
      <?php if ($this->description): ?><div class="public-list-desc"><?= $this->markdown()->toHtml($this->description) ?></div><?php endif ?>
      <?php if ($this->date): ?>
        <div class="public-list-info">
          <div><?= $this->transEsc("modified"); ?>: <?=$this->dateTime()->convertToDisplayDate('Y-m-d H:i:s', $this->date); ?></div>
        </div>
      <?php endif ?>
    </div>
  </div>
  <div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->params->getView())?>">
    <?= $this->partial('Helpers/userlist-content.phtml',
    [
      'results' => $this->results,
      'params' => $this->params,
      'view' => $this->view,
      'indexStart' => $this->indexStart,
      'hideCartControls' => true
    ])
    ?>
    <a class="load-more" data-id="<?= $this->escapeHtmlAttr($this->id)?>" data-view="<?= $this->escapeHtmlAttr($this->view)?>" data-start-index="<?= $this->escapeHtmlAttr($this->indexStart + $this->params->getLimit())?>" data-offset="<?= $this->escapeHtmlAttr($this->params->getLimit())?>">Show all</a>
  </div>
</div>
<?php
$this->headScript()->appendFile("finna-userlist-embed.js");
$js = <<<JS
$(document).ready(function(){
  finna.userListEmbed.init();
});
JS;
$this->headScript()->appendScript($js);
?>