<!-- START of: finna - ajax/authority-recommend.phtml -->
<?php
/*
$data = $this->recommend->getRecommendations();
if (empty($data)) {
  return;
}
$activeInd = count($data) ? count($data)-1 : 0;
*/
$results = $this->recommend->getResults();
$that = $this;
$record = $this->authority; //data[$activeInd];
$formats = $record->getFormats();
$formatter = $this->recordDataFormatter();
$coreFields = $formatter->getDefaults('authority');
?>
    <h3 property="name" class="record-title"><?=$this->escapeHtml($record->getTitle())?></h3>
    <div class="resultItemFormat"><i class="fa fa-authority-<?=$this->escapeHtmlAttr($this->record($record)->getFormatClass($formats[0]))?>"></i> <?=$this->translate('authority_' . $formats[0])?></div>
    <?php if ($roles = $this->recommend->getRoles($record->getUniqueID())): ?>
    <strong><?=$this->translate('Role')?>:</strong>
    <ul class="roles">
        <?php foreach ($roles as $role): ?>
        <li>
            <?php if (!$role['enabled']): ?>
            <a href="<?=$results->getUrlQuery()->setAuthorIdWithRole($record->getUniqueID(), $role['value'])?>">
            <?php endif; ?>
                <?=$role['role']?> (<?=$role['count']?>)
                <?php if (!$role['enabled']): ?>
            </a>
                <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    <?php $summ = $record->getSummary(); if (!empty($summ)): ?>
    <div class="wide recordSummary truncate-field" data-rows="5">
        <p class="summary">
            <?php foreach ($summ as $field): ?>
            <?// NOTE: the driver is responsible for returning only safe tags ?>
            <?=$field?><br/>
            <?php endforeach; ?>
        </p>
    </div>
    <?php endif; ?>
    <?php $coreFields = $formatter->getData($record, $coreFields); ?>
    <?php if (!empty($coreFields)): ?>
    <table class="table table-finna-record record-details">
        <?=$this->record($record)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
    </table>
    <?php endif; ?>
<!-- END of: finna - ajax/authority-recommend.phtml -->
