<!-- START of: finna - ajax/dynamic-list-list.phtml -->
<div class="dynamic-list-type">
    <h3><a href="<?=$this->url('dynamic-list-results')?>?query=<?=$this->query?>"><?=$this->transEsc("dynamic_list_$this->query")?></a></h3>
</div>
<ul class="dynamic-list-list content">
    <?php foreach ($this->records as $ind => $record): ?>
        <?php
            $ilsDetails = $record->getExtraDetail('ils_details');
            $isRecord = is_a($record, 'VuFind\\RecordDriver\\SolrDefault');
            $formats = $record->tryMethod('getFormats');
            $format = $isRecord && $formats ? $this->record($record)->getFormatClass(end($formats)) : 'book';
            $thumb = $thumb = $isRecord ? $this->recordImage($this->record($record))->getLargeImage() . '&w=1024&h=1024&imgext=.jpeg' : false;
            $author = $isRecord ? $record->getPrimaryAuthorForSearch() : $ilsDetails['author'];
            $year = $isRecord ? ($record->getPublicationDates()[0] ?? '') : $ilsDetails['year'];
        ?>
        <li class="dynamic-list-item">
            <?php if ($thumb && $isRecord): ?>
                <div class="image-wrapper">
                    <img class="dynamic-list-image" src="<?=$this->escapeHtmlAttr($thumb)?>" alt="kansikuva">
                </div>
            <?php endif; ?>
            <div class="dynamic-list-icon <?= ($isRecord && $thumb ? 'hidden' : '');?>">
                <div class="iconlabel format-<?=$format?>"></div>
            </div>
            <div class="dynamic-list-title">
                <?php if ($isRecord): ?>
                    <a href="<?= $this->url('record', ['id' => $ilsDetails['id']])?>">
                <?php endif; ?>
                <p class="item-title"><?= substr($record->getTitle(), 0, 40); ?></p>
                <?php if ($isRecord): ?>
                    </a>
                <?php endif; ?>
                <?php if ($isRecord): ?>
                    <p><?=$this->record($record)->getFormatList() ?> <?=$this->record($record)->getSourceIdElement() ?></p>
                <?php endif; ?>
                <p><?= $this->escapeHtml($author);?></p>
                <p><?= $this->escapeHtml($year);?></p>
            </div>
        </div>
    <?php endforeach; ?>
</ul>
<!-- END of: finna - ajax/dynamic-list-carousel.phtml -->
