<!-- START of: finna - ajax/title-list-carousel.phtml -->
<div class="title-list-type">
    <h3><a href="<?=$this->url('ils-title-list')?>?query=<?=$this->query?>&id=<?=$this->sourceId?>"><?= $this->transEsc("title_list_$this->query") ?></a></h3>
</div>

<div class="title-list-carousel content">
    <?php foreach ($this->records as $ind => $record): ?>
        <?php
            $ilsDetails = $record->getExtraDetail('ils_details');
            $isRecord = is_a($record, 'VuFind\\RecordDriver\\SolrDefault');
            $formats = $record->tryMethod('getFormats');
            $format = $isRecord && $formats ? $this->record($record)->getFormatClass(end($formats)) : 'book';
            $thumb = $isRecord ? $this->recordImage($this->record($record))->getLargeImage() . '&w=1024&h=1024&imgext=.jpeg' : false;
            $author = $isRecord ? $record->getPrimaryAuthorForSearch() : $ilsDetails['author'];
            $year = $isRecord ? ($record->getPublicationDates()[0] ?? '') : $ilsDetails['year'];
        ?>
        <div class="title-list-item">
            <?php if ($isRecord): ?>
                <a href="<?=$this->recordLink()->getUrl($record)?>">
            <?php endif; ?>
            <div class="title-list-title">
                <p><?= substr($record->getTitle(), 0, 40); ?></p>
                <div class="hidden-default">
                    <?php if ($isRecord): ?>
                        <p><?=$this->record($record)->getFormatList() ?> <?=$this->record($record)->getSourceIdElement() ?></p>
                    <?php endif; ?>
                    <p><?= $this->escapeHtml($author);?></p>
                    <p><?= $this->escapeHtml($year);?></p>
                </div>
            </div>
            <?php if ($isRecord && $thumb): ?>
                <div class="image-wrapper">
                    <img class="title-list-image" data-lazy="<?=$this->escapeHtmlAttr($thumb)?>" alt="<?=$this->transEsc("Cover Image");?>">
                </div>
            <?php endif; ?>
            <div class="title-list-icon <?= ($isRecord && $thumb ? 'hidden' : '');?>">
                <span class="iconlabel format-<?=$format?>"></span>
            </div>
            <?php if ($isRecord): ?>
                </a>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<!-- END of: finna - ajax/title-list-carousel.phtml -->
