<div class="carousel">
  <? if ($this->title || $this->translateTitle): ?><h2 class="carousel-header"><?= $this->translateTitle ? $this->transEsc($this->translateTitle) : $this->title; ?></h2><? endif; ?>
  <div class="carousel-feed">
    <? foreach($this->items as $item): ?>
    <div>
      <? if (!isset($this->linkText) && isset($item['link'])):?><a<?= $this->linkTarget ? ' target="' . $this->escapeHtml($this->linkTarget) . '"' : '' ?> href="<?= $item['link']; ?>"><? endif; ?>  
      <? if (isset($item['title'])): ?>
      <div class="carousel-slide-header">
        <p><?= $item['title']; ?></p>
      </div>
      <? endif; ?>
      <? if (isset($item['text']) || $this->linkText): ?>
      <div class="carousel-text">
        <? if (isset($item['text'])): ?><p><?= $item['text']; ?>
        <? if (isset($item['link']) && $this->linkText): ?><a <?= $this->linkTarget ? ' target="' . $this->escapeHtml($this->linkTarget) . '"' : '' ?> href="<?= $item['link']; ?>" class="carousel-link"><?=$this->transEsc($this->linkText)?></a><? endif; ?>
        </p><? endif; ?>
      </div>
      <? endif; ?>
      <? if (isset($item['image']) && isset($item['image']['url'])): ?>
      <div class="wrapper">
        <img src="<?= $item['image']['url']; ?>" />
      </div>
      <? endif; ?>
      <? if (isset($item['link'])):?></a><? endif; ?>
    </div>
    <? endforeach; ?>
  </div>
</div>