<!--
<?= var_export($this->statusItems, true) ?>
-->

<?
  $availableBranches = null;
  $availableItems = null;
  $itemsTotal = null;
  $reservations = null;
  $closestDueDate = null;
  array_walk_recursive(
    $this->statusItems,
    function ($val, $key) use (
      &$availableBranches, &$availableItems, &$itemsTotal, &$reservations, &$closestDueDate
    ) {
      if ($key == 'availability' && $val) {
        $availableBranches++;
      } else if ($key == 'available') {
        $availableItems += $val;
      } else if ($key == 'total') {    
        $itemsTotal += $val;   
      } else if ($key == 'reservations' && $val > $reservations) {
        $reservations = $val;
      } else if ($key == 'duedate' && !empty($val) && (empty($closestDueDate) || strtotime($val) < $closestDueDate)) {
        $closestDueDate = strtotime($val);
      }
    }
  );

  $groupBranches = isset($this->statusItems[0]['branch']);
  $journal = isset($this->statusItems[0]['journalInfo']);
  if ($groupBranches) {
    $prevLocation = null;
    $currentLocation = null;
    $collapsed = true; // TODO: branchCnt > threshold
  }
?>

<? if ($groupBranches): ?>
<div>
  <div class="header <?= $availableItems ? 'available' : ''?>">
    <i class="fa fa-<?= $availableItems ? 'ok' : 'remove'?>"></i>
    <span>
      <? if ($availableItems > 0): ?>
        <?=sprintf('%s %d %s', $this->transEsc('axiell_available'), $availableBranches, $this->transEsc($journal ? 'axiell_issues' : 'axiell_branches'));?>
      <? elseif ($closestDueDate): ?>
        <?=sprintf('%s %s %s', $this->transEsc('status_Charged'), $this->transEsc('Due Date'), date('j.n.Y', $closestDueDate));?>
      <? else: ?>
        <?=$this->transEsc('status_Charged')?>
      <? endif; ?>
    </span>
    <? if (!$journal): ?>
    <span><?=sprintf('%s %d, %s %d', $this->transEsc('Requests'), $reservations, $this->transEsc('axiell_items'), $itemsTotal);?></span>
    <? endif; ?>
  </div>
  <? if ($collapsed): ?>
    <div class="locations collapsed">
  <? else: ?>
    <div class="truncate-field" data-rows="5">
  <? endif; ?>
<? else: ?>
<div>
<? endif; ?>

<?
$collapsed = false;

foreach ($this->statusItems as $item):
    $newLocation = false;
    if ($groupBranches && $currentLocation != $item['location']) {
      $prevLocation = $currentLocation;
      $currentLocation = $item['location'];
      $newLocation = true;
      $collapsed = true;
    }
?>

<? if ($groupBranches && $newLocation && $prevLocation): ?>
  </div>
<? endif; ?>
<? if ($groupBranches && $newLocation): ?>  
  <div class="groupLocation"><span><?=$currentLocation?></span><span><?=$this->escapeHtml($item['callnumber'])?></span>
<? endif; ?>
  <div class="groupLocation">
    <?
      $classes = null;    
      if ($item['availability']) {
        $classes = ['ok', 'success'];
      }
      if (!$classes && $item['status_unknown']) {
        $classes = ['remove', 'warning'];
      }
      if (!$classes) {
        $classes = ['remove', 'error'];
      }
      $location = $groupBranches ? "{$item['branch']}, {$item['department']}" : $item['location'];    
    ?>
    
    <i class="fa fa-<?=$classes[0]?> text-<?=$classes[1]?>"></i> <span class="text-<?=$class?>"><?= $this->transEsc('location_' . $location, [], $location); ?></span>
    <? if ($groupBranches): ?>
    <span class="branchInfo">
      <? if ($item['availability']): ?>
        <?= sprintf('%s %d', $this->transEsc('Available items'), $item['availabilityInfo']['available']); ?>
      <? elseif (!empty($item['duedate']) && !$item['availability']): ?>
        <?= str_replace('%%date%%', $item['duedate'], $this->transEsc('closest_due_date')); ?>
      <? elseif ($item['availabilityInfo']['ordered'] > 0): ?>
        <?= sprintf('%s %d', $this->transEsc('status_Ordered'), $item['availabilityInfo']['ordered']); ?>
      <? else: ?>
        <?= $this->transEsc('status_' . $item['availabilityInfo']['displayText']); ?></span>
      <? endif; ?>
    <? else: ?>
    <span class="groupCallnumber"><?=$this->escapeHtml($item['callnumber'])?></span>    
    <? endif; ?>
  </div>
  
<? endforeach; ?>
<? if ($groupBranches): ?>
</div>
<? endif; ?>

</div>
<div>Varaa teos</div>
<div>kaikki saatavuustiedot</div>

<!--
<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Call Number')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <? $i = 0; foreach ($this->statusItems as $item): ?>
    <? if (++$i == 5) break; // Show no more than 5 items ?>
    <tr>
      <td>
        <? $locationText = $this->transEsc('location_' . $item['location'], array(), $item['location']); ?>
        <? if (isset($item['locationhref']) && $item['locationhref']): ?>
          <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
        <? else: ?>
          <?=$locationText?>
        <? endif; ?>
      </td>
      <td><?=$this->escapeHtml($item['callnumber'])?></td>
      <td>
        <? if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
          <span><?=$this->transEsc("status_unknown_message")?></span>
        <? elseif ($item['availability']): ?>
          <span class="text-success"><?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?></span>
        <? else: ?>
          <span class="text-danger"><?=$this->transEsc($item['status'])?></span>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
<? if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', array('id' => $this->statusItems[0]['id']))?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more')?> ...</a></td></tr>
<? endif; ?>
</table>
-->