<!--
<?= var_export($this->statusItems, true) ?>
-->

<?
$groupBranches = isset($this->statusItems[0]['branch']);
if ($groupBranches) {
  $journal = isset($this->statusItems[0]['journalInfo']);

  $availableTotal = $itemsTotal = $reservationsTotal = 0;
  $locations = $availableLocations = $closestDueDateInBranch = [];
  $illRequestLink = false;
  
  foreach ($this->statusItems as $item) {
    if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']) {
      $illRequestLink = $row['ILLRequestLink'];
    }

    if (!empty($item['availability'])) {
      $availableTotal++;
      if (empty($availableLocation[$item['location']])) {
        $availableLocations[$item['location']] = 0;
      }
      $availableLocations[$item['location']]++;
    }
    if (isset($item['availabilityInfo']['total'])) {
        $itemsTotal += $item['availabilityInfo']['total'];
    } else {
        $itemsTotal++;
    }
    
    if (!empty($item['duedate'])) {
      $duedate = strtotime($item['duedate']);
      if (empty($closestDueDateInLocation[$item['location']])
      || $duedate < $closestDueDateInLocation[$item['location']]
    ) {
        $closestDueDateInLocation[$item['location']] = $duedate;
      }
    }
    if (isset($item['availabilityInfo']['reservations'])) {
      $reservations
      = max($reservationsTotal, $item['availabilityInfo']['reservations']);
    }
    
    $locations[$item['location']] = true;
  }
  
  if (!empty($closestDueDateInLocation)) {
    $closestDueDate = date('j.n.Y', min(array_values($closestDueDateInLocation)));
    foreach ($closestDueDateInLocation as &$duedate) {
      $duedate = date('j.n.Y', $duedate);
    }
  }

  $collapseThreshold = $this->holdingsSettings()->getCollapseThreshold();
  $collapseLocations
    = isset($collapseThreshold['location'])
    ? count($locations) > $collapseThreshold['location']
    : null
  ;
  $collapseBranches
    = isset($collapseThreshold['branch'])
    ? count($this->statusItems) > $collapseThreshold['branch']
    : null
  ;
}
?>

<? if ($groupBranches): ?>
<div class="holdings-container root <?=$collapseLocations ? ' collapsible' : ''?>">
  <div class="header <?= $availableTotal ? 'available' : ''?>">
    <i class="fa fa-<?= $availableTotal ? 'ok' : 'remove'?>"></i>
    <span>
      <? if ($availableTotal): ?>
        <?=sprintf('%s %d %s', $this->transEsc('axiell_available'), $availableTotal, $this->transEsc($journal ? 'axiell_issues' : 'axiell_branches'));?>
      <? elseif ($closestDueDate): ?>
        <?=sprintf('%s %s %s', $this->transEsc('status_Charged'), $this->transEsc('Due Date'), $closestDueDate);?>
      <? else: ?>
        <?=$this->transEsc('status_Charged')?>
      <? endif; ?>
    </span>
    <? if ($collapseLocations): ?><i class="fa fa-arrow-right arrow"></i><? endif; ?>
    <? if (!$journal): ?>
    <span class="info"><?=sprintf('%s: %d, %s: %d', $this->transEsc('Requests'), $reservations, $this->transEsc('axiell_items'), $itemsTotal);?></span>
    <? endif; ?>
  </div>
  <div class="holdings<?=$collapseLocations ? ' collapsed' : ''?> root">
<? else: ?>
<div class="truncate-field" data-rows="5">
<? endif; ?>

<?
$currentLocation = $prevLocation = $currentOrganisation = $prevOrganisation = null;

foreach ($this->statusItems as $item):
  if ($groupBranches) {
    $newLocation = false;
    $newOrganisation = false;
    if ($currentLocation != $item['location']) {
      $prevLocation = $currentLocation;
      $currentLocation = $item['location'];
      $newLocation = true;
      if ($journal) {
        $prevOrganisation = $currentOrganisation = $item['journalInfo']['location'];
      }
    } else if ($journal && $currentOrganisation != $item['journalInfo']['location']) {
      $prevOrganisation = $currentOrganisation;
      $currentOrganisation = $item['journalInfo']['location'];
      $newOrganisation = true;
    }
  }
?>

<? if ($groupBranches && $newLocation && $prevLocation): ?>
  </div></div>
<? endif; ?>
<? if ($groupBranches && $newLocation): ?>  
  <div class="holdings-container<?=$collapseBranches ? ' collapsible' : ''?>">
    <div class="header">
        <? if ($collapseBranches): ?><i class="fa fa-arrow-right arrow"></i><? endif; ?>
        <?=$currentLocation?>
        <? if ($collapseBranches): ?>
        <span>
          <? if (!empty($availableLocations[$item['location']])): ?>
            <?=sprintf('(%s %d %s)', $this->transEsc('axiell_available'), $availableLocations[$item['location']], $this->transEsc($journal ? 'axiell_issues' : 'axiell_branches'));?>
          <? elseif (!empty($closestDueDateInLocation[$item['location']])): ?>
            <?= str_replace('%%date%%', $closestDueDateInLocation[$item['location']], $this->transEsc('closest_due_date')); ?>
          <? else: ?>
            (<?=$this->transEsc('status_' . $item['status'])?>)          
          <? endif; ?>
        </span>
        <? endif; ?>
      <span class="info"><?=$this->escapeHtml($item['callnumber'])?></span>
    </div>
  <div class="holdings<?=$collapseBranches ? ' collapsible collapsed' : ''?>">    
<? endif; ?>
    <?
      $classes = null;    
      if ($item['availability']) {
        $classes = ['ok', 'success'];
      }
      if (!$classes && $item['status_unknown']) {
        $classes = ['remove', 'warning'];
      }
      if (!$classes) {
        $classes = ['remove', 'error'];
      }
      $location
        = $groupBranches
        ? '<span class="branch">' . ($this->transEsc($item['branch']) . '</span>, <span class="department">' . $this->transEsc($item['department']) . '</span>')
        : '<span class="branch">' . $this->transEsc($item['location'], [], $item['location']) . '</span>';    
    ?>
    <div<?= $prevOrganisation && $newOrganisation ? ' class="new-organisation"' : ''; ?>>
      <i class="fa fa-<?=$classes[0]?> text-<?=$classes[1]?>"></i> <span class="text-<?=$classes[0]?>"><?=$location?></span>
      <? if ($groupBranches): ?>
        <span class="branchInfo">
        <? if ($item['availability'] && !empty($item['availabilityInfo']['available'])): ?>
          <?= sprintf('%s: %d', $this->transEsc('Available items'), $item['availabilityInfo']['available']); ?>
        <? elseif (!empty($item['duedate']) && !$item['availability']): ?>
          <?= str_replace('%%date%%', $item['duedate'], $this->transEsc('closest_due_date')); ?>
        <? elseif ($item['availabilityInfo']['ordered'] > 0): ?>
          <?= sprintf('%s: %d', $this->transEsc('status_Ordered'), $item['availabilityInfo']['ordered']); ?>
        <? else: ?>
          <?= $this->transEsc('status_' . $item['availabilityInfo']['displayText']); ?></span>
        <? endif; ?>
      <? else: ?>
        <span class="groupCallnumber"><?=$this->escapeHtml($item['callnumber'])?></span>    
      <? endif; ?>
    </div>
<? endforeach; ?>
  </div>

<? if ($groupBranches): ?>
</div>
<? endif; ?>
</div>

<div class="actions">
<?
if ($this->holdingsSettings()->showSearchResultsTitleHold()) {
  $id = $this->statusItems[0]['id'];
  $driver = $this->record($id)->getDriver();
  if ($driver->tryMethod('getHoldsAllowed')) {
    $holdingTitleHold = $driver->tryMethod('getRealTimeTitleHold');
    if (!empty($holdingTitleHold)) {
?>
    <div class="title-hold">
      <a class="placehold modal-link btn btn-primary hidden-print" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"> <?=$this->transEsc('title_hold_place')?></a>
    </div>
<?
    }
  }
}
?>
<? if ($this->holdingsSettings()->showLinkToRecordPage()): ?>
  <div class="all-holdings">
    <a href="<?=sprintf('%s%s/Holdings#tabnav', $this->url('record'), $this->statusItems[0]['id']);?>"><?=$this->transEsc('See all holdings')?></a>
  </div>
<? endif; ?>
</div>

