<div class="daterange-vis">
  <?= $this->partial('Recommend/DateRangeForm.phtml', [
    'from' => $from,
    'to' => $to,
    'formAction' => $formAction,
    'type' => $type
  ]); ?>

  <div class="content">
    <? $this->headScript()->appendFile('vendor/jquery.flot.canvas.min.js', 'text/javascript', ['conditional' => 'IE']); ?> 
    <? $this->headScript()->appendFile('vendor/jquery.flot.min.js'); ?>
    <? $this->headScript()->appendFile('vendor/jquery.flot.selection.min.js'); ?>
    <? $this->headScript()->appendFile('finna-daterange-vis.js'); ?>
    
    <div class="navigation">
      <div class="zoom-in"><i class="fa fa-plus"></i></div>
      <div class="zoom-out"><i class="fa fa-minus"></i></div>
      <div class="prev"><i class="fa fa-arrow-left"></i></div>
      <div class="next"><i class="fa fa-arrow-right"></i></div>
    </div>
    
    <div class="date-vis"></div>
    <i class="fa fa-spinner fa-spin"></i>
  </div>
</div>

<?
$script = <<<JS
$(document).ready(function() {
  finna.dateRangeVis.initVis(
      '{$this->searchParams}',
      '{$this->formAction}',
      $('.daterange-vis')
  );
});
JS;
?>
  
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>



