<div class="daterange-vis">
  <?= $this->partial('Recommend/DateRangeForm.phtml', [
    'submitLabel' => $submitLabel,
    'from' => $from,
    'to' => $to,
    'formAction' => $formAction,
    'type' => $type,
    'backend' => $backend,
    'hideType' => isset($hideType) ? $hideType : false
  ]); ?>

  <div class="content">
    <? $this->headScript()->appendFile('vendor/jquery.flot.min.js'); ?>
    <? $this->headScript()->appendFile('vendor/jquery.flot.selection.min.js'); ?>
    <? $this->headScript()->appendFile('finna-daterange-vis.js'); ?>
    
    <div class="navigation">
      <div class="zoom-in"><i class="fa fa-plus"></i></div>
      <div class="zoom-out"><i class="fa fa-minus"></i></div>
      <div class="prev"><i class="fa fa-arrow-left"></i></div>
      <div class="next"><i class="fa fa-arrow-right"></i></div>
    </div>
    
    <div class="date-vis"></div>
    <i class="fa fa-spinner fa-spin"></i>
  </div>
</div>


<?
$script = <<<JS
$(document).ready(function() {
  finna.dateRangeVis.initVis(
      '{$backend}',
      '{$daterangeFacet}',
      '{$daterangeFacetOperator}',
      '{$searchParams}',
      '{$baseParams}',
      $('.daterange-vis'),
JS;

$script .= isset($this->plotFrom) ? "{$this->plotFrom}," : 'false,';
$script .= isset($this->plotTo) ? "{$this->plotTo}," : 'false,';
$script .= isset($this->plotImmediately) ? "true" : "false";
$script .= '
  );
});';

?>
  
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>



