<?php if (!empty($labels)): ?>
  <ul class="record-labels">
    <?php foreach ($labels as $label): ?>
      <?php
        $tooltip = "RecordLabelTooltip:{$label}_html";
        if (!$this->translationEmpty($tooltip)) {
          $replace = [];
          if ($label === 'r2_restricted_metadata_available') {
            $replace = ['%%register%%' => $this->url('r2feedback-form', ['id' => 'R2Register']), '%%terms%%' => $this->url('myresearch-r2termsofuse')];
          }
          $tooltip = $this->translate($tooltip, $replace);
        } else {
          $tooltip = null;
        }
      ?>
      <li class="label iconlabel <?=str_replace('_', '-', $label)?><?= $tooltip ? ' with-tooltip' : '' ?>"<?= $tooltip ? (' data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="' . $this->escapeHtmlAttr($tooltip) . '"') : '' ?>><?=$this->transEsc($label)?></li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
