<div class="container">
  <div class="record record-row missing">
    <?= $this->flashmessages() ?>
    <?php if ($this->warning): ?>
      <div class="alert alert-danger"><?= $this->transEsc($this->warning)?></div>
    <?php endif ?>
    <?php if (!$this->hasAccess): ?>
      <?= $this->R2RestrictedRecordRegister(null, ['user' => $this->auth()->isLoggedIn()]) ?>
    <?php endif ?>
  </div>
</div>
