<?php if ($this->results): ?>
<div class="related-records">
  <h1><?=$this->transEsc('Related Items')?></h1>
  <ul class="list-group">
    <?php foreach ($this->results as $type => $records): ?>
      <?php if (!empty($records)): ?>
        <li class="list-group-item">
          <p><?=$this->transEsc("record_driver_related:$type")?></p>
          <ul>
          <?php foreach ($records as $record): ?>
          <?php $formats = $record->getFormats(); ?>
            <li>
              <i class="fa fa-<?php if (count($formats) > 0): ?> fa-<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>" title="<?=$formats[0] ?><?php endif; ?>"></i>
              <a href="<?=$this->recordLink()->getUrl($record)?>">
                <?=$this->escapeHtml($record->getTitle())?>
              </a>
            </li>
          <?php endforeach; ?>
          </ul>
        </li>
      <?php endif ?>
    <?php endforeach; ?>
  </ul>
</div>
<?php endif; ?>
