<div class="recordcover-holder">
<?
$images = null;
if (count($allImages)) {
  $images = $allImages;
} else if ($largeImage) {
  $images = array(array('small' => $smallImage, 'medium' => $mediumImage, 'large' => $largeImage));
}
$imageData = array('images' => $images, 'type' => $type);
$formats = $this->driver->tryMethod('getFormats');
$formatClass = $this->record($this->driver)->getFormatClass(end($formats));
?>

<? if ($images): ?>
  <?= $this->partial('RecordDriver/SolrDefault/record-image-navi.phtml', $imageData) ?>
<? endif; ?>

<? if ($mediumImage): ?>
<a class="image-popup-trigger" href="<?= $this->recordLink()->getUrl($this->driver) ?>#image">
<? if (count($allImages) <= 1): ?>
  <div class="iconlabel format-<?=$formatClass?>"></div>
<? endif; ?>
  <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumImage);?>"/>
  <i class="fa fa-magnify hidden-print"></i>
</a>
<? else: ?>
<div class="image-popup-trigger no-image">
  <div class="iconlabel format-<?=$formatClass?>"></div>
  <div class="no-cover recordcover"></div>
</div>
<? endif; ?>

</div>
